# Dependencies
markdown:         kramdown
highlighter: rouge
encoding: utf-8

# Permalinks
permalink:        pretty

# Setup
title:            METANOIA
tagline:          'Blog pessoal.'
description:      'Blog pessoal.'
url:              http://metanoia.blog.br

author:
  name:           'Érico Rodrigues'
  url:            https://www.facebook.com/EricoRodrigues11

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/metanoia39/metanoia.github.io

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
